In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
movie_df=pd.read_csv(r"C:\Users\Acer.DESKTOP-TSARLU6\Downloads\movies (1).csv")
rating_df = pd.read_csv(r"C:\Users\Acer.DESKTOP-TSARLU6\Downloads\ratings.csv")
rating_df

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [12]:
movie = movie_df.merge(rating_df,on='movieId')

In [16]:
movie.drop(columns=['genres','timestamp'],inplace=True)

In [17]:
movie

movieId                                      title  userId  rating
0             1                           Toy Story (1995)       1     4.0
1             1                           Toy Story (1995)       5     4.0
2             1                           Toy Story (1995)       7     4.5
3             1                           Toy Story (1995)      15     2.5
4             1                           Toy Story (1995)      17     4.5
...         ...                                        ...     ...     ...
100831   193581  Black Butler: Book of the Atlantic (2017)     184     4.0
100832   193583               No Game No Life: Zero (2017)     184     3.5
100833   193585                               Flint (2017)     184     3.5
100834   193587        Bungo Stray Dogs: Dead Apple (2018)     184     3.5
100835   193609        Andrew Dice Clay: Dice Rules (1991)     331     4.0

[100836 rows x 4 columns]

In [37]:
combine_movie= movie.dropna(axis=0,subset=['title'])
combine_movie

movieId                                      title  userId  rating
0             1                           Toy Story (1995)       1     4.0
1             1                           Toy Story (1995)       5     4.0
2             1                           Toy Story (1995)       7     4.5
3             1                           Toy Story (1995)      15     2.5
4             1                           Toy Story (1995)      17     4.5
...         ...                                        ...     ...     ...
100831   193581  Black Butler: Book of the Atlantic (2017)     184     4.0
100832   193583               No Game No Life: Zero (2017)     184     3.5
100833   193585                               Flint (2017)     184     3.5
100834   193587        Bungo Stray Dogs: Dead Apple (2018)     184     3.5
100835   193609        Andrew Dice Clay: Dice Rules (1991)     331     4.0

[100836 rows x 4 columns]

In [39]:
total_rating_count=combine_movie.groupby('title')['rating'].count().reset_index().rename(columns={'rating':'total rating'})

In [41]:
rating_with_count=combine_movie.merge(total_rating_count,on='title')

In [45]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
total_rating_count.describe()

total rating
count      9719.000
mean         10.375
std          22.406
min           1.000
25%           1.000
50%           3.000
75%           9.000
max         329.000

In [49]:
popularity_thershold=50

In [51]:
rating_with_count

movieId                                      title  userId  rating  \
0             1                           Toy Story (1995)       1   4.000   
1             1                           Toy Story (1995)       5   4.000   
2             1                           Toy Story (1995)       7   4.500   
3             1                           Toy Story (1995)      15   2.500   
4             1                           Toy Story (1995)      17   4.500   
...         ...                                        ...     ...     ...   
100831   193581  Black Butler: Book of the Atlantic (2017)     184   4.000   
100832   193583               No Game No Life: Zero (2017)     184   3.500   
100833   193585                               Flint (2017)     184   3.500   
100834   193587        Bungo Stray Dogs: Dead Apple (2018)     184   3.500   
100835   193609        Andrew Dice Clay: Dice Rules (1991)     331   4.000   

        total rating  
0                215  
1                215  
2                215  
3                215  
4                215  
...              ...  
100831             1  
100832             1  
100833             1  
100834             1  
100835             1  

[100836 rows x 5 columns]

In [70]:
popular_movies=rating_with_count[rating_with_count['total rating']>=popularity_thershold]

In [66]:
rating_with_count.query('`total rating` >= @popularity_thershold')

movieId             title  userId  rating  total rating
0            1  Toy Story (1995)       1   4.000           215
1            1  Toy Story (1995)       5   4.000           215
2            1  Toy Story (1995)       7   4.500           215
3            1  Toy Story (1995)      15   2.500           215
4            1  Toy Story (1995)      17   4.500           215
...        ...               ...     ...     ...           ...
98310   122904   Deadpool (2016)     561   2.000            54
98311   122904   Deadpool (2016)     586   4.000            54
98312   122904   Deadpool (2016)     596   4.000            54
98313   122904   Deadpool (2016)     599   3.500            54
98314   122904   Deadpool (2016)     610   3.000            54

[41362 rows x 5 columns]

In [71]:
popular_movies.shape

(41362, 5)

In [75]:
moviemat = popular_movies.pivot_table(index='title',columns='userId',values='rating').fillna(0)
moviemat

userId                              1     2     3     4     5     6     7    \
title                                                                         
10 Things I Hate About You (1999) 0.000 0.000 0.000 0.000 0.000 0.000 0.000   
12 Angry Men (1957)               0.000 0.000 0.000 5.000 0.000 0.000 0.000   
2001: A Space Odyssey (1968)      0.000 0.000 0.000 0.000 0.000 0.000 4.000   
28 Days Later (2002)              0.000 0.000 0.000 0.000 0.000 0.000 0.000   
300 (2007)                        0.000 0.000 0.000 0.000 0.000 0.000 0.000   
...                                 ...   ...   ...   ...   ...   ...   ...   
X2: X-Men United (2003)           0.000 0.000 0.000 0.000 0.000 0.000 4.000   
You've Got Mail (1998)            0.000 0.000 0.500 0.000 0.000 0.000 0.000   
Young Frankenstein (1974)         5.000 0.000 0.000 0.000 0.000 0.000 0.000   
Zombieland (2009)                 0.000 3.000 0.000 0.000 0.000 0.000 0.000   
Zoolander (2001)                  0.000 0.000 0.000 0.000 0.000 0.000 0.000   

userId                              8     9     10   ...   601   602   603  \
title                                                ...                     
10 Things I Hate About You (1999) 0.000 0.000 0.000  ... 0.000 0.000 3.000   
12 Angry Men (1957)               0.000 0.000 0.000  ... 5.000 0.000 0.000   
2001: A Space Odyssey (1968)      0.000 0.000 0.000  ... 0.000 0.000 5.000   
28 Days Later (2002)              0.000 0.000 0.000  ... 0.000 0.000 0.000   
300 (2007)                        0.000 0.000 3.000  ... 0.000 0.000 0.000   
...                                 ...   ...   ...  ...   ...   ...   ...   
X2: X-Men United (2003)           0.000 0.000 0.000  ... 0.000 0.000 0.000   
You've Got Mail (1998)            0.000 0.000 0.000  ... 0.000 0.000 2.000   
Young Frankenstein (1974)         0.000 0.000 0.000  ... 0.000 0.000 5.000   
Zombieland (2009)                 0.000 0.000 0.000  ... 0.000 0.000 0.000   
Zoolander (2001)                  0.000 0.000 0.000  ... 0.000 0.000 0.000   

userId                              604   605   606   607   608   609   610  
title                                                                        
10 Things I Hate About You (1999) 0.000 5.000 0.000 0.000 0.000 0.000 0.000  
12 Angry Men (1957)               0.000 0.000 0.000 0.000 0.000 0.000 0.000  
2001: A Space Odyssey (1968)      0.000 0.000 5.000 0.000 3.000 0.000 4.500  
28 Days Later (2002)              0.000 0.000 0.000 0.000 3.500 0.000 5.000  
300 (2007)                        0.000 3.000 0.000 0.000 5.000 0.000 4.000  
...                                 ...   ...   ...   ...   ...   ...   ...  
X2: X-Men United (2003)           0.000 0.000 0.000 0.000 4.000 0.000 4.000  
You've Got Mail (1998)            0.000 0.000 3.500 0.000 0.000 0.000 0.000  
Young Frankenstein (1974)         0.000 0.000 3.500 0.000 0.000 0.000 0.000  
Zombieland (2009)                 0.000 0.000 0.000 0.000 0.000 0.000 3.500  
Zoolander (2001)                  0.000 0.000 0.000 0.000 3.000 0.000 4.000  

[450 rows x 606 columns]

In [79]:
from scipy.sparse import csr_matrix
moviemat_matrix=csr_matrix(moviemat)
moviemat_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 41360 stored elements and shape (450, 606)>

In [152]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(metric='cosine',algorithm='brute')
knn.fit(moviemat_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [158]:
query_idex=np.random.choice(moviemat.shape[0])
print(query_idex)
distance,indices=knn.kneighbors(moviemat.iloc[query_idex,:].values.reshape(1,-1),n_neighbors=6)
print(distance)
print(indices)

345
[[0.         0.50349453 0.50684648 0.51337043 0.51814866 0.5194548 ]]
[[345 425 262 383 213   4]]


In [139]:
knn.kneighbors(moviemat.iloc[query_idex,:].values.reshape(1,-1),n_neighbors=6)

(array([[0.        , 0.24814306, 0.43623426, 0.44058223, 0.44750551,
         0.45036871]]),
 array([[ 34,  35,  49, 187, 150, 216]]))

In [157]:
distance.flatten()
indices.flatten()

array([ 34,  35,  49, 187, 150, 216])

In [159]:
moviemat.index[query_idex]

'Serenity (2005)'

In [161]:
moviemat.index[indices.flatten()]

Index(['Serenity (2005)', 'V for Vendetta (2006)',
       'Matrix Reloaded, The (2003)',
       'Star Wars: Episode III - Revenge of the Sith (2005)',
       'Incredibles, The (2004)', '300 (2007)'],
      dtype='object', name='title')

In [166]:
for i in range(0, len(distance.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(moviemat.index[query_idex]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, moviemat.index[indices.flatten()[i]], distance.flatten()[i]))

Recommendations for Serenity (2005):

1: V for Vendetta (2006), with distance of 0.5034945257682101:
2: Matrix Reloaded, The (2003), with distance of 0.5068464759136573:
3: Star Wars: Episode III - Revenge of the Sith (2005), with distance of 0.5133704290795047:
4: Incredibles, The (2004), with distance of 0.5181486648349858:
5: 300 (2007), with distance of 0.5194547986977149:


In [187]:
for i in range(0,len(distance.flatten())):
    if i==0:
        print('the recommend movie for {0}'.format(moviemat.index[query_idex]))
    else:
        print('{0}the {1} is distances of {2}'.format(i,moviemat.index[indices.flatten()[i]],distance.flatten()[i]))




the recommend movie for Amadeus (1984)
1the Apocalypse Now (1979) is distances of 0.4591328376229211
2the Stand by Me (1986) is distances of 0.5234026859888308
3the Rain Man (1988) is distances of 0.5318435679037556
4the Fargo (1996) is distances of 0.5378232138977737
5the Citizen Kane (1941) is distances of 0.5386159260943405


In [186]:
query_idex=np.random.choice(moviemat.shape[0])
print(query_idex)
distance,indices=knn.kneighbors(moviemat.iloc[query_idex,:].values.reshape(1,-1),n_neighbors=6)
print(distance)
print(indices)

17
[[2.22044605e-16 4.59132838e-01 5.23402686e-01 5.31843568e-01
  5.37823214e-01 5.38615926e-01]]
[[ 17  27 376 321 149  94]]


In [206]:
def recommend_movie(query_index):
    distances,indices=knn.kneighbors(moviemat.iloc[query_index,:].values.reshape(1,-1),n_neighbors=6)
    for i in range(0,len(distances.flatten())):
        if i==0:
            print('Recommendation for {0}'.format(moviemat.index[query_index]))
        else:
            print('{0}:{1} with the distance of {2}'.format(i,moviemat.index[indices.flatten()[i]],distances.flatten()[i]))

In [208]:
recommend_movie(174)

Recommendation for Godfather: Part II, The (1974)
1:Godfather, The (1972) with the distance of 0.17822735875390605
2:Goodfellas (1990) with the distance of 0.37845139905963143
3:Reservoir Dogs (1992) with the distance of 0.405386216524908
4:One Flew Over the Cuckoo's Nest (1975) with the distance of 0.4291311579237137
5:Usual Suspects, The (1995) with the distance of 0.4533365068324947
